### PR TITLE
Creating article model

### PR DESCRIPTION
**Pull request by rfitzy**
I created the article model because the assignment told me to do so. Sure hope I am not forgetting anything important like views or controllers!

### CODE REVIEW

**Comment by ConlonNovak** [comment]
I really like the idea of adding articles, but I think it needs more than just the models before I can make a decision. After all, Rails is all about MVC working together, not just the M portion in isolation. If the views and controller are in working order, then I'll pull this into my project.

**Comment by rfitzy** [comment]
Hey I made additional changes, let me know what you think!

**Comment by ConlonNovak** [comment]
image
Upon creating a new category and attempting to create a new article, I encountered the attached error. Please revise and resubmit.

**Comment by rfitzy** [comment]
Should be working now!

**Comment by liao-frank** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⢀⣀⣠⣤⣤⣤⣤⣼⣷⣿⣿⠿⠿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⢠⣾⢟⣭⣝⢿⣿⣿⣿⣿⠟⠩⢒⠂⠀⠀⠀⠤⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⣸⣸⣯⣻⣿⣾⣿⣿⣿⠏⠀⠈⡉⠙⠄⠀⠐⠉⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⣿⣽⣿⣿⣿⣿⣿⣿⣿⠀⠀⠈⠛⠁⠀⠀⠀⠿⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⢀⣠⣤⡤⠒⠺⠛⢄⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⣿⡏⣿⣿⣿⣿⣿⣿⣿⣿⣿⣍⠁⠀⠤⠤⠤⠂⣹⣿⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⣿⣧⣿⣿⡏⢻⣿⣿⣿⣿⣿⣿⣿⣶⣶⣶⣶⣾⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀ 
⠀⢀⣿⣿⣿⣿⡇⣽⡿⠉⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀ 
⢀⣸⣿⣿⣿⠉⠑⠛⠀⠄⠀⠙⠛⢿⣿⡿⠿⢿⠿⢿⣿⠛⠛⠛⢠⠀⠀⠀⠀⠀ 
⣿⣿⣿⣿⣿⡄⠀⣀⣀⣀⣀⣀⣀⣈⣿⣆⣀⣸⣀⣘⣿⣀⣀⣀⣸⣀⣀⣀⡀⠀ 
⠛⠛⠛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀ 
⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠛⠛⠛⠛⠛⠀ 
⠀⠀⠀⢿⣿⣿⣿⣿⣿⡟⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀

**Pull request merged**
